service: bug-demo
# org: ilanc
# app: bug-demo

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  stage: dev
  # stage: prod

functions:
  hello:
    handler: hello.main.get
    events:
      - httpApi:
          method: GET
          path: /hello
